# Generated by Django 5.1.2 on 2024-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_truyen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="title_full",
            field=models.CharField(default="noname", max_length=255),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
