# Generated by Django 5.1.2 on 2024-11-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_truyen", "0002_story_description_story_image_story_title_full_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="name_full",
            field=models.CharField(default="noname", max_length=50),
        ),
        migrations.AddField(
            model_name="genre",
            name="page_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="chapter_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
