# Generated by Django 5.1.2 on 2024-11-04 10:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_truyen", "0003_genre_name_full_genre_page_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="chapter_number",
        ),
        migrations.RemoveField(
            model_name="story",
            name="genres",
        ),
        migrations.AddField(
            model_name="story",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=3
            ),
        ),
    ]
