# Generated by Django 5.1.2 on 2024-11-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_truyen", "0004_remove_story_chapter_number_remove_story_genres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="chapter_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="genres",
            field=models.ManyToManyField(
                related_name="stories",
                through="app_truyen.StoryGenre",
                to="app_truyen.genre",
            ),
        ),
    ]
