# Generated by Django 5.1.2 on 2024-11-04 13:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_truyen", "0005_story_chapter_number_story_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=4
            ),
        ),
    ]
